name: Deploy to PROD
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: 8

    - name: Download artifact from Exchange
      run: |
        # Get the commit hash to identify the artifact
        commitHash=$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")
        echo "Looking for artifact with commit hash: $commitHash"
        
        # Download from Exchange using Maven
        mvn dependency:copy \
        -Dartifact=${{ secrets.GROUP_ID }}:${{ github.event.repository.name }}:${{ github.event.pull_request.head.ref }} \
        -DoutputDirectory=target \
        --settings .maven/settings.xml \
        -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
        -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

    - name: Deploy to CloudHub PROD
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
        -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
        -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
        -Denvironment=PROD